[tool.poetry]
name = "Fanfiction-Finder"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"
async-timeout = "^3.0.1"
attrs = "^21.2.0"
beautifulsoup4 = "^4.9.3"
certifi = "^2021.5.30"
chardet = "^4.0.0"
cloudscraper = "^1.2.58"
"discord.py" = "^1.7.3"
Flask = "^2.0.1"
idna = "^2.10"
multidict = "^5.1.0"
pyparsing = "^2.4.7"
python-dotenv = "^0.17.1"
requests-toolbelt = "^0.9.1"
soupsieve = "^2.2.1"
typing-extensions = "^3.10.0"
urllib3 = "^1.26.5"
yarl = "^1.6.3"
waitress = "^2.0.0"
requests = "^2.25.1"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
