[tool.poetry]
name = "Fanfiction-Finder"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.7.4"
async-timeout = "^3.0.1"
attrs = "^20.3.0"
autopep8 = "^1.5.4"
beautifulsoup4 = "^4.9.3"
certifi = "^2020.12.5"
"discord.py" = "^1.7.3"
et-xmlfile = "^1.0.1"
flake8 = "^3.8.4"
idna = "^3.1"
waitress = "^1.4.4"
Flask = "^1.1.2"
importlib-metadata = "^3.4.0"
jdcal = "^1.4.1"
mccabe = "^0.6.1"
multidict = "^5.1.0"
pycodestyle = "^2.6.0"
pyflakes = "^2.2.0"
python-dateutil = "^2.8.1"
python-dotenv = "^0.15.0"
pytz = "^2020.5"
six = "^1.15.0"
toml = "^0.10.2"
typing-extensions = "^3.7.4"
wheel = "^0.36.2"
yarl = "^1.6.3"
zipp = "^3.4.0"
chardet = "^4.0.0"
cloudscraper = "^1.2.58"
lockfile = "^0.12.2"
lxml = "^4.6.3"
pyparsing = "^2.4.7"
requests-toolbelt = "^0.9.1"
soupsieve = "^2.2.1"
urllib3 = "^1.26.5"
python-dotenv = "^0.17.1"
waitress = "^2.0.0"
Flask = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
